# Netlify Deployment Configuration

## Build Settings
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_GA_ID = "G-FSP1DKFFWV"

## Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
